services:


# SERVICES


  gateway:
    build: ./gateway
    ports:
      - "39999:39999"
    depends_on:
      - otel-collector
      - nats
      - redis

  classroom:
    build: ./classroom
    ports:
      - "40000:40000"
    depends_on:
      - otel-collector
      - classroom-db
      - gateway

  classroom-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 130924
    ports:
      - "40001:5432"

  locker:
    build: ./locker
    ports:
      - "40002:40002"
    depends_on:
      - locker-db
      - gateway

  locker-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 130924
    ports:
      - "40003:5432"

  teacher:
    build: ./teacher
    ports:
      - "40004:40004"
    depends_on:
      - teacher-db
      - gateway

  teacher-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 130924
    ports:
      - "40005:5432"

  notification:
    build: ./notification
    depends_on:
      - nats
      - gateway


# REDIS


  redis:
    image: redis:8
    ports:
      - "6379:6379"


# NATS


  nats:
    image: nats:2.14.0
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ "-js", "-m", "8222" ]


# MONITORING


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.151.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./monitoring/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - jaeger
      - loki
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.70.0
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:v3.3.1
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.7.0
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:13.0.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - jaeger
      - loki
      - prometheus