services:
  classroom:
    build: ./classroom
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  classroom-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 130924
    ports:
      - "1987:5432"

  redis:
    image: redis:8
    ports:
      - "6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.151.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./monitoring/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - jaeger
      - loki
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.70.0
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:v3.3.1
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.7.0
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:13.0.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - jaeger
      - loki
      - prometheus