Server:
  ClassroomGrpcSrvAddr: classroom:40000
  LockerGrpcSrvAddr: locker:40002
  TeacherGrpcSrvAddr: teacher:40004

Http:
  Port: 39999
  PprofPort: 6060
  ReadHeaderTimeout: 5
  ReadTimeout: 15
  WriteTimeout: 15
  IdleTimeout: 60
  MaxHeaderBytes: 1048576

Telemetry:
  Name: "gateway"
  Endpoint: otel-collector:4317

Redis:
  Addr: redis:6379
  Password: ""
  DB: 0
  MaxRetries: 3