Server:
  ClassroomGrpcSrvAddr: classroom:40000
  LockerGrpcSrvAddr: locker:40002
  TeacherGrpcSrvAddr: teacher:40004

Http:
  Port: 39999
  PprofPort: 6060
  ReadHeaderTimeout: 5s
  ReadTimeout: 15s
  WriteTimeout: 15s
  IdleTimeout: 60s
  MaxHeaderBytes: 1048576

Telemetry:
  Name: "gateway"
  Endpoint: otel-collector:4317

Redis:
  Addr: redis:6379
  Password: ""
  DB: 0
  MaxRetries: 3

Nats:
  Addr: nats://nats:4222
  NotificationSubject: notification